"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Activity,AlertTriangle,ArrowRight,CalendarDays,CarFront,Check,CircleDollarSign,Clock3,FileText,Gauge,LayoutDashboard,Menu,Plus,Search,Settings,ShieldCheck,Users,Wrench,X} from "lucide-react";

type Vehicle={id:string;name:string;category:string;seats:number;rate:number;deposit:number;type:string;transmission:string};
type FleetRecord={id:string;daily_rate_override:number|null;deposit_override:number|null;vehicle_models:{manufacturer:string;model_name:string;variant:string|null;transmission:string|null;passenger_capacity:number|null;rental_type:string|null;daily_rate_override:number|null;deposit_override:number|null;vehicle_categories:{name:string;daily_rate:number;security_deposit:number;default_rental_type:string;passenger_capacity:number}}|null};
const adminDemoFleet:Vehicle[]=[
 {id:"APC-001",name:"Toyota Vios",category:"Sedan",seats:5,rate:1800,deposit:3000,type:"Self-drive",transmission:"Automatic"},
 {id:"APC-002",name:"Toyota Fortuner",category:"SUV",seats:7,rate:3500,deposit:5000,type:"Self-drive",transmission:"Automatic"},
 {id:"APC-003",name:"Toyota Hiace",category:"Van",seats:12,rate:4500,deposit:6000,type:"With driver",transmission:"Manual"}];
const rows=[
 {ref:"CR-20260903-00125",customer:"Maria Santos",vehicle:"Toyota Fortuner · FTN-002",trip:"Sep 8, 8:00 AM – Sep 9, 5:00 PM",status:"Awaiting settlement",time:"00:28:16",amount:"₱8,500"},
 {ref:"CR-20260903-00124",customer:"Paolo Reyes",vehicle:"Toyota Vios · VIO-004",trip:"Today, 10:00 AM – Tomorrow, 10:00 AM",status:"Ready for release",time:"—",amount:"₱4,500"},
 {ref:"CR-20260902-00119",customer:"Angela Lim",vehicle:"Mitsubishi Strada · STR-001",trip:"Sep 2, 7:00 AM – Today, 7:00 AM",status:"Overdue",time:"02h 18m",amount:"₱7,040"}];
const peso=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n);

function Policy(){
 return <div className="policy"><div><Clock3/><span><b>4-hour reservation hold</b><small>Settle onsite before the hold expires.</small></span></div><div><ShieldCheck/><span><b>Admin approval required</b><small>A request is not yet a confirmed rental.</small></span></div><div><CalendarDays/><span><b>Release & return: 7 AM–9 PM</b><small>Scheduled times must fall within store hours.</small></span></div></div>
}
function Brand(){return <a className="brand"><i><CarFront/></i><b>RoadReady<small>Vehicle Rental</small></b></a>}
function Customer({goAdmin}:{goAdmin:()=>void}){
 const[step,setStep]=useState(1),[category,setCategory]=useState("All"),[selected,setSelected]=useState<Vehicle|null>(null),[sent,setSent]=useState(false),[menu,setMenu]=useState(false),[fleet,setFleet]=useState<Vehicle[]>([]),[fleetLoading,setFleetLoading]=useState(true),[fleetError,setFleetError]=useState("");
 useEffect(()=>{let active=true;async function loadFleet(){const supabase=createClient();const{data,error}=await supabase.from("vehicles").select("id,daily_rate_override,deposit_override,vehicle_models!inner(manufacturer,model_name,variant,transmission,passenger_capacity,rental_type,daily_rate_override,deposit_override,vehicle_categories!inner(name,daily_rate,security_deposit,default_rental_type,passenger_capacity))").eq("status","ACTIVE").eq("operational_status","AVAILABLE");if(!active)return;if(error){setFleetError("Live vehicle availability could not be loaded. Please try again.");setFleetLoading(false);return}const mapped=((data||[]) as unknown as FleetRecord[]).flatMap((unit)=>{const m=unit.vehicle_models;if(!m)return[];const c=m.vehicle_categories;return[{id:unit.id,name:[m.manufacturer,m.model_name,m.variant].filter(Boolean).join(" "),category:c.name,seats:m.passenger_capacity||c.passenger_capacity,rate:unit.daily_rate_override??m.daily_rate_override??c.daily_rate,deposit:unit.deposit_override??m.deposit_override??c.security_deposit,type:(m.rental_type||c.default_rental_type)==="WITH_DRIVER"?"With driver":"Self-drive",transmission:m.transmission||"Not specified"}]});setFleet(mapped);setFleetLoading(false)}loadFleet();return()=>{active=false}},[]);
 const shown=category==="All"?fleet:fleet.filter(v=>v.category===category);
 if(sent)return <main className="customer"><Header goAdmin={goAdmin} menu={menu} setMenu={setMenu}/><section className="confirm"><i><Check/></i><p className="eyebrow">Booking request received</p><h1>Your schedule is held for 4 hours.</h1><p>Visit the rental store and settle before the reservation expires. Your booking remains subject to Admin approval.</p><div className="timer"><small>Reservation held for</small><b>03:59:42</b><span>Until Sep 3, 2026 at 1:18 PM</span></div><div className="summary"><div><small>Booking reference</small><b>CR-20260903-00131</b></div><div><small>Vehicle</small><b>{selected?.name}</b></div><div><small>Rental period</small><b>Sep 10, 8:00 AM — Sep 12, 6:00 PM</b></div><div><small>Estimate with deposit</small><b>{peso((selected?.rate||0)*2+(selected?.deposit||0))}</b></div></div><Policy/><button className="primary" onClick={()=>setSent(false)}>Track booking <ArrowRight/></button></section></main>;
 return <main className="customer"><Header goAdmin={goAdmin} menu={menu} setMenu={setMenu}/><section className="hero"><div><p className="eyebrow">Drive on your terms</p><h1>A better way to rent your next ride.</h1><p>Clear rates, real availability, and a guided booking flow—made for stress-free trips.</p><div className="checks"><span><Check/>Transparent pricing</span><span><Check/>Verified fleet</span><span><Check/>Local support</span></div></div><div className="car-art"><CarFront/></div></section>
 <section className="book"><div className="steps">{["Schedule","Vehicle","Details","Requirements","Review"].map((x,i)=><button key={x} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>setStep(i+1)}><i>{step>i+1?<Check/>:i+1}</i>{x}</button>)}</div>
 {step===1&&<div className="stage"><Heading n={1} title="When do you need a vehicle?"/><Policy/><div className="fields four"><label>Pickup date<input type="date" defaultValue="2026-09-10"/></label><label>Pickup time<select><option>08:00 AM</option></select></label><label>Expected return date<input type="date" defaultValue="2026-09-12"/></label><label>Expected return time<select><option>06:00 PM</option></select></label></div><Footer next={()=>setStep(2)} label="Check available vehicles"/></div>}
 {step===2&&<div className="stage"><Heading n={2} title="Choose your vehicle"/><div className="filters">{["All",...Array.from(new Set(fleet.map(v=>v.category)))].map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div>{fleetLoading?<p className="fleet-message">Checking live fleet availability…</p>:fleetError?<p className="fleet-message error">{fleetError}</p>:shown.length===0?<p className="fleet-message">No vehicles are currently available for this selection. Please contact the rental store for assistance.</p>:<div className="vehicles">{shown.map(v=><article className={selected?.id===v.id?"selected":""} key={v.id}><div className="vehicle-art"><CarFront/></div><div><small>{v.category}</small><h3>{v.name}</h3><p>{v.transmission} · {v.seats} passengers · {v.type}</p><footer><span>From <b>{peso(v.rate)}</b> / day</span><button onClick={()=>setSelected(v)}>{selected?.id===v.id?"Selected":"Select"}</button></footer></div></article>)}</div>}<Footer back={()=>setStep(1)} next={()=>selected&&setStep(3)} label="Continue" disabled={!selected}/></div>}
 {step>=3&&<div className="stage"><Heading n={step} title={step===3?"Tell us about you":step===4?"Upload your requirements":"Review your booking"}/>
 {step===3&&<div className="fields two"><label>First name<input defaultValue="Nigel"/></label><label>Last name<input placeholder="Last name"/></label><label>Mobile number<input placeholder="09XX XXX XXXX"/></label><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Complete address<input placeholder="Street, barangay, city"/></label><label>Destination<input placeholder="Where are you going?"/></label></div>}
 {step===4&&<div className="uploads">{["Primary valid ID","Secondary valid ID","Driver’s license"].map(x=><button key={x}><Plus/><b>{x}</b><small>Tap to upload front and back</small></button>)}</div>}
 {step===5&&<div className="review"><div><small>Vehicle</small><b>{selected?.name}</b><span>{selected?.type} · {selected?.seats} passengers</span></div><div><small>Schedule</small><b>Sep 10, 8:00 AM — Sep 12, 6:00 PM</b><span>2-day rental</span></div><div><small>Rental + deposit</small><b>{peso((selected?.rate||0)*2+(selected?.deposit||0))}</b><span>Rates freeze after approval</span></div><Policy/></div>}
 <Footer back={()=>setStep(step-1)} next={()=>step<5?setStep(step+1):setSent(true)} label={step<5?"Continue":"Submit booking request"}/></div>}</section>
 <section className="assurance"><div><ShieldCheck/><b>Protected information</b><small>Identity documents stay private.</small></div><div><CircleDollarSign/><b>No hidden pricing</b><small>See rates before submission.</small></div><div><Users/><b>Local support</b><small>Staff review every request.</small></div></section></main>
}
function Header({goAdmin,menu,setMenu}:{goAdmin:()=>void;menu:boolean;setMenu:(v:boolean)=>void}){return <header><Brand/><nav className={menu?"open":""}><a>Fleet</a><a>How it works</a><a>Policies</a><a>Track booking</a><button onClick={goAdmin}>Staff portal</button></nav><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button></header>}
function Heading({n,title}:{n:number;title:string}){return <div className="heading"><div><p className="eyebrow">Step {n} of 5</p><h2>{title}</h2></div><span><i/> Live availability</span></div>}
function Footer({back,next,label,disabled}:{back?:()=>void;next:()=>void;label:string;disabled?:boolean}){return <footer className="stage-foot">{back?<button className="secondary" onClick={back}>Back</button>:<span>Times shown in Asia/Manila</span>}<button className="primary" disabled={disabled} onClick={next}>{label}<ArrowRight/></button></footer>}

const nav=[["Dashboard",LayoutDashboard],["Bookings",CalendarDays],["Customers",Users],["Fleet",CarFront],["Inspections",ShieldCheck],["Finance",CircleDollarSign],["Maintenance",Wrench],["Reports",FileText],["Activity log",Activity],["Settings",Settings]] as const;
function Admin({goCustomer}:{goCustomer:()=>void}){
 const[tab,setTab]=useState("Dashboard"),[query,setQuery]=useState(""),[voidRef,setVoidRef]=useState<string|null>(null),[toast,setToast]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>(r.ref+r.customer+r.vehicle).toLowerCase().includes(query.toLowerCase())),[query]);
 return <main className="admin"><aside><Brand/><nav>{nav.map(([x,I])=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}><I/>{x}{x==="Bookings"&&<em>7</em>}</button>)}</nav><button className="customer-link" onClick={goCustomer}><ArrowRight/>Customer site</button><div className="profile"><i>NN</i><span><b>Nigel Nimes</b><small>Owner</small></span></div></aside><section className="admin-main"><header><div><small>Thursday, September 3</small><h1>{tab}</h1></div><div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search bookings, customers, plates…"/></label><button><Plus/>New booking</button></div></header>
 {toast&&<div className="toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}
 {tab==="Dashboard"?<Dashboard data={filtered} voidIt={setVoidRef} setTab={setTab}/>:tab==="Bookings"?<Bookings data={filtered} voidIt={setVoidRef}/>:tab==="Fleet"?<Fleet/>:tab==="Finance"?<Finance/>:<Module name={tab}/>}</section>
 {voidRef&&<div className="backdrop"><div className="modal"><i><AlertTriangle/></i><h2>Void booking request?</h2><p>This removes <b>{voidRef}</b> from active queues and immediately releases its vehicle/time-slot hold. Its audit record remains.</p><label>Reason<select><option>Customer entered wrong information</option><option>Customer changed rental details</option><option>Duplicate request</option><option>Wrong vehicle</option><option>Wrong rental schedule</option><option>Customer cancelled</option><option>Other</option></select></label><label>Internal note<textarea placeholder="Add a short explanation…"/></label><footer><button onClick={()=>setVoidRef(null)}>Keep request</button><button className="danger" onClick={()=>{setVoidRef(null);setToast("Booking voided. Its hold is now released.")}}>Void and release hold</button></footer></div></div>}</main>
}
function Dashboard({data,voidIt,setTab}:{data:typeof rows;voidIt:(x:string)=>void;setTab:(x:string)=>void}){return <><div className="warning"><AlertTriangle/><span><b>3 reservations expire within the next hour</b><small>Review onsite settlement status to prevent unintended releases.</small></span><button onClick={()=>setTab("Bookings")}>Review holds <ArrowRight/></button></div><div className="metrics">{([["Pending approval","7","2 new",Clock3],["Active rentals","12","3 return today",CarFront],["Overdue","2","₱1,050 est. overtime",AlertTriangle],["Available fleet","18","of 36 operational",Gauge],["Payments today","₱48,500","14 transactions",CircleDollarSign]] as [string,string,string,typeof Clock3][]).map(([a,b,c,I])=><article key={a}><I/><small>{a}</small><b>{b}</b><span>{c}</span></article>)}</div><Table data={data} voidIt={voidIt}/><div className="columns"><section className="panel"><PanelHead title="Today’s movement" sub="Scheduled pickups and returns"/>{[["10:00 AM","Pickup","Paolo Reyes","Toyota Vios · VIO-004"],["1:00 PM","Pickup","Jose Villanueva","Toyota Hiace · HIA-002"],["7:00 PM","Return","Angela Lim","Mitsubishi Strada · STR-001"]].map(x=><div className="movement" key={x[0]}><b>{x[0]}</b><em>{x[1]}</em><span><b>{x[2]}</b><small>{x[3]}</small></span><button>Open</button></div>)}</section><section className="panel"><PanelHead title="Attention needed" sub="Fleet and compliance alerts"/>{["Registration expires in 6 days","Post-rental inspection pending","Maintenance due at 42,000 km"].map((x,i)=><div className="attention" key={x}><i className={"c"+i}/><span><b>{x}</b><small>{["Toyota Vios · VIO-002","Toyota Innova · INV-001","Toyota Fortuner · FTN-003"][i]}</small></span><ArrowRight/></div>)}</section></div></>}
function PanelHead({title,sub}:{title:string;sub:string}){return <div className="panel-head"><span><h2>{title}</h2><p>{sub}</p></span><button>View all <ArrowRight/></button></div>}
function Table({data,voidIt,all=false}:{data:typeof rows;voidIt:(x:string)=>void;all?:boolean}){return <section className="panel"><PanelHead title={all?"Active bookings":"Reservations awaiting onsite settlement"} sub={all?"Shared lifecycle, payment, and availability status":"Urgent holds first · server time is authoritative"}/><div className="table"><table><thead><tr><th>Booking</th><th>Customer / vehicle</th><th>Rental schedule</th><th>Status</th><th>{all?"Amount":"Time remaining"}</th><th/></tr></thead><tbody>{data.map(r=><tr key={r.ref}><td><b>{r.ref}</b><small>Online request</small></td><td><b>{r.customer}</b><small>{r.vehicle}</small></td><td>{r.trip}</td><td><em className={"s-"+r.status.split(" ")[0].toLowerCase()}>{r.status}</em></td><td><strong>{all?r.amount:r.time}</strong></td><td><button>Open</button><button onClick={()=>voidIt(r.ref)}>•••</button></td></tr>)}</tbody></table></div></section>}
function Bookings({data,voidIt}:{data:typeof rows;voidIt:(x:string)=>void}){return <div className="module"><div className="module-head"><span><h2>Booking workspace</h2><p>All requests and rental transactions</p></span><button><Plus/>Walk-in booking</button></div><Table data={data} voidIt={voidIt} all/></div>}
function Fleet(){return <div className="module"><div className="module-head"><span><h2>Fleet catalog</h2><p>Category → model → physical vehicle unit</p></span><button><Plus/>Add vehicle</button></div><div className="stats">{[["Categories","5"],["Models","14"],["Physical units","36"],["Available now","18"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="table"><table><thead><tr><th>Vehicle model</th><th>Category</th><th>Units</th><th>Daily rate</th><th>Deposit</th><th>Visibility</th></tr></thead><tbody>{adminDemoFleet.map((v,i)=><tr key={v.name}><td><b>{v.name}</b><small>{v.transmission} · {v.seats} seats</small></td><td>{v.category}</td><td>{i+2} units</td><td><b>{peso(v.rate)}</b><small>Preview data</small></td><td>{peso(v.deposit)}</td><td><em className="s-ready">Admin preview</em></td></tr>)}</tbody></table></div><div className="rate-note"><Settings/><span><b>Rates are inherited, never hard-coded</b><small>Category defaults can be overridden by model or unit. Approved bookings keep a pricing snapshot.</small></span><button>Edit rates</button></div></div>}
function Finance(){return <><div className="metrics finance">{[["Collected this month","₱382,400","+12.4% vs Aug"],["Outstanding","₱42,800","18 bookings"],["Deposits held","₱91,000","22 active deposits"],["Refunds pending","₱8,500","3 settlements"]].map(x=><article key={x[0]}><CircleDollarSign/><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><div className="module"><div className="module-head"><span><h2>Transaction ledger</h2><p>Balances derive from charges, payments, deposits, and reversals</p></span><button><Plus/>Record payment</button></div>{[["PAY-0924","Payment · Cash","CR-20260903-00124","+ ₱4,500","Posted"],["CHG-0923","Base rental","CR-20260903-00124","₱1,500","Posted"],["DEP-0922","Security deposit","CR-20260903-00124","+ ₱3,000","Held"],["CHG-0921","Overtime · 3 hours","CR-20260902-00119","₱450","Estimated"]].map(x=><div className="ledger" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span><strong>{x[3]}</strong><em>{x[4]}</em></div>)}</div></>}
function Module({name}:{name:string}){return <div className="empty"><i><Settings/></i><h2>{name}</h2><p>This operational workspace is connected to the same authoritative rental lifecycle and audit trail.</p><button className="primary">Open {name.toLowerCase()} <ArrowRight/></button></div>}
export default function Home(){const[admin,setAdmin]=useState(false);return admin?<Admin goCustomer={()=>setAdmin(false)}/>:<Customer goAdmin={()=>setAdmin(true)}/>}
