"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Activity,AlertTriangle,ArrowRight,CalendarDays,CarFront,Check,CircleDollarSign,Clock3,FileText,Gauge,LayoutDashboard,Menu,Plus,Search,Settings,ShieldCheck,Users,Wrench,X} from "lucide-react";

type Vehicle={id:string;name:string;category:string;seats:number;rate:number;deposit:number;type:string;transmission:string};
type FleetRecord={id:string;daily_rate_override:number|null;deposit_override:number|null;vehicle_models:{manufacturer:string;model_name:string;variant:string|null;transmission:string|null;passenger_capacity:number|null;rental_type:string|null;daily_rate_override:number|null;deposit_override:number|null;vehicle_categories:{name:string;daily_rate:number;security_deposit:number;default_rental_type:string;passenger_capacity:number}}|null};
type BookingReceipt={booking_reference:string;reservation_expires_at:string;vehicle_name:string;rental_days:number;estimated_total:number;required_deposit:number};
type BookingRow={id:string;ref:string;customer:string;vehicle:string;trip:string;status:string;time:string;amount:string};
const adminDemoFleet:Vehicle[]=[
 {id:"APC-001",name:"Toyota Vios",category:"Sedan",seats:5,rate:1800,deposit:3000,type:"Self-drive",transmission:"Automatic"},
 {id:"APC-002",name:"Toyota Fortuner",category:"SUV",seats:7,rate:3500,deposit:5000,type:"Self-drive",transmission:"Automatic"},
 {id:"APC-003",name:"Toyota Hiace",category:"Van",seats:12,rate:4500,deposit:6000,type:"With driver",transmission:"Manual"}];
const peso=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n);

function Policy(){
 return <div className="policy"><div><Clock3/><span><b>4-hour reservation hold</b><small>Settle onsite before the hold expires.</small></span></div><div><ShieldCheck/><span><b>Admin approval required</b><small>A request is not yet a confirmed rental.</small></span></div><div><CalendarDays/><span><b>Release & return: 7 AM–9 PM</b><small>Scheduled times must fall within store hours.</small></span></div></div>
}
function Brand(){return <a className="brand"><i><CarFront/></i><b>RoadReady<small>Vehicle Rental</small></b></a>}
function Customer({goAdmin}:{goAdmin:()=>void}){
 const[step,setStep]=useState(1),[category,setCategory]=useState("All"),[selected,setSelected]=useState<Vehicle|null>(null),[sent,setSent]=useState(false),[menu,setMenu]=useState(false),[fleet,setFleet]=useState<Vehicle[]>([]),[fleetLoading,setFleetLoading]=useState(true),[fleetError,setFleetError]=useState("");
 const[pickupDate,setPickupDate]=useState("2026-09-10"),[pickupTime,setPickupTime]=useState("08:00"),[returnDate,setReturnDate]=useState("2026-09-12"),[returnTime,setReturnTime]=useState("18:00");
 const[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[mobile,setMobile]=useState(""),[email,setEmail]=useState(""),[address,setAddress]=useState(""),[destination,setDestination]=useState(""),[passengers,setPassengers]=useState(1);
 const[receipt,setReceipt]=useState<BookingReceipt|null>(null),[submitting,setSubmitting]=useState(false),[submitError,setSubmitError]=useState("");
 useEffect(()=>{let active=true;async function loadFleet(){const supabase=createClient();const{data,error}=await supabase.from("vehicles").select("id,daily_rate_override,deposit_override,vehicle_models!inner(manufacturer,model_name,variant,transmission,passenger_capacity,rental_type,daily_rate_override,deposit_override,vehicle_categories!inner(name,daily_rate,security_deposit,default_rental_type,passenger_capacity))").eq("status","ACTIVE").eq("operational_status","AVAILABLE");if(!active)return;if(error){setFleetError("Live vehicle availability could not be loaded. Please try again.");setFleetLoading(false);return}const mapped=((data||[]) as unknown as FleetRecord[]).flatMap((unit)=>{const m=unit.vehicle_models;if(!m)return[];const c=m.vehicle_categories;return[{id:unit.id,name:[m.manufacturer,m.model_name,m.variant].filter(Boolean).join(" "),category:c.name,seats:m.passenger_capacity||c.passenger_capacity,rate:unit.daily_rate_override??m.daily_rate_override??c.daily_rate,deposit:unit.deposit_override??m.deposit_override??c.security_deposit,type:(m.rental_type||c.default_rental_type)==="WITH_DRIVER"?"With driver":"Self-drive",transmission:m.transmission||"Not specified"}]});setFleet(mapped);setFleetLoading(false)}loadFleet();return()=>{active=false}},[]);
 const shown=category==="All"?fleet:fleet.filter(v=>v.category===category);
 async function submitBooking(){if(!selected)return;setSubmitting(true);setSubmitError("");const supabase=createClient();const{data,error}=await supabase.rpc("create_public_booking",{p_vehicle_id:selected.id,p_first_name:firstName,p_last_name:lastName,p_mobile_number:mobile,p_email:email,p_complete_address:address,p_destination:destination,p_passenger_count:passengers,p_pickup_at:`${pickupDate}T${pickupTime}:00+08:00`,p_expected_return_at:`${returnDate}T${returnTime}:00+08:00`,p_customer_notes:null});setSubmitting(false);if(error){setSubmitError(error.message);return}setReceipt(data as BookingReceipt);setSent(true)}
 const scheduleText=`${pickupDate} ${pickupTime} — ${returnDate} ${returnTime}`;
 if(sent&&receipt)return <main className="customer"><Header goAdmin={goAdmin} menu={menu} setMenu={setMenu}/><section className="confirm"><i><Check/></i><p className="eyebrow">Booking request received</p><h1>Your schedule is held for 4 hours.</h1><p>Visit the rental store and settle before the reservation expires. Your booking remains subject to Admin approval.</p><div className="timer"><small>Reservation deadline</small><b>4 hours</b><span>{new Date(receipt.reservation_expires_at).toLocaleString("en-PH",{timeZone:"Asia/Manila",dateStyle:"medium",timeStyle:"short"})}</span></div><div className="summary"><div><small>Booking reference</small><b>{receipt.booking_reference}</b></div><div><small>Vehicle</small><b>{receipt.vehicle_name}</b></div><div><small>Rental period</small><b>{scheduleText}</b></div><div><small>Estimate with deposit</small><b>{peso(receipt.estimated_total)}</b></div></div><Policy/><button className="primary" onClick={()=>{setSent(false);setStep(1);setSelected(null)}}>Make another booking <ArrowRight/></button></section></main>;
 return <main className="customer"><Header goAdmin={goAdmin} menu={menu} setMenu={setMenu}/><section className="hero"><div><p className="eyebrow">Drive on your terms</p><h1>A better way to rent your next ride.</h1><p>Clear rates, real availability, and a guided booking flow—made for stress-free trips.</p><div className="checks"><span><Check/>Transparent pricing</span><span><Check/>Verified fleet</span><span><Check/>Local support</span></div></div><div className="car-art"><CarFront/></div></section>
 <section className="book"><div className="steps">{["Schedule","Vehicle","Details","Requirements","Review"].map((x,i)=><button key={x} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>setStep(i+1)}><i>{step>i+1?<Check/>:i+1}</i>{x}</button>)}</div>
 {step===1&&<div className="stage"><Heading n={1} title="When do you need a vehicle?"/><Policy/><div className="fields four"><label>Pickup date<input type="date" value={pickupDate} onChange={e=>setPickupDate(e.target.value)}/></label><label>Pickup time<input type="time" min="07:00" max="21:00" value={pickupTime} onChange={e=>setPickupTime(e.target.value)}/></label><label>Expected return date<input type="date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label><label>Expected return time<input type="time" min="07:00" max="21:00" value={returnTime} onChange={e=>setReturnTime(e.target.value)}/></label></div><Footer next={()=>setStep(2)} label="Check available vehicles" disabled={!pickupDate||!returnDate||!pickupTime||!returnTime}/></div>}
 {step===2&&<div className="stage"><Heading n={2} title="Choose your vehicle"/><div className="filters">{["All",...Array.from(new Set(fleet.map(v=>v.category)))].map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div>{fleetLoading?<p className="fleet-message">Checking live fleet availability…</p>:fleetError?<p className="fleet-message error">{fleetError}</p>:shown.length===0?<p className="fleet-message">No vehicles are currently available for this selection. Please contact the rental store for assistance.</p>:<div className="vehicles">{shown.map(v=><article className={selected?.id===v.id?"selected":""} key={v.id}><div className="vehicle-art"><CarFront/></div><div><small>{v.category}</small><h3>{v.name}</h3><p>{v.transmission} · {v.seats} passengers · {v.type}</p><footer><span>From <b>{peso(v.rate)}</b> / day</span><button onClick={()=>setSelected(v)}>{selected?.id===v.id?"Selected":"Select"}</button></footer></div></article>)}</div>}<Footer back={()=>setStep(1)} next={()=>selected&&setStep(3)} label="Continue" disabled={!selected}/></div>}
 {step>=3&&<div className="stage"><Heading n={step} title={step===3?"Tell us about you":step===4?"Upload your requirements":"Review your booking"}/>
 {step===3&&<div className="fields two"><label>First name<input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="First name"/></label><label>Last name<input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Last name"/></label><label>Mobile number<input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="09XX XXX XXXX"/></label><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com"/></label><label>Complete address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Street, barangay, city"/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Where are you going?"/></label><label>Passenger count<input type="number" min="1" max={selected?.seats||99} value={passengers} onChange={e=>setPassengers(Number(e.target.value))}/></label></div>}
 {step===4&&<div className="uploads">{["Valid government-issued ID","Driver’s license"].map(x=><button key={x}><Plus/><b>{x}</b><small>Upload a clear front and back image</small></button>)}</div>}
 {step===5&&<div className="review"><div><small>Vehicle</small><b>{selected?.name}</b><span>{selected?.type} · {selected?.seats} passengers</span></div><div><small>Schedule</small><b>{scheduleText}</b><span>Asia/Manila time</span></div><div><small>Estimated rental + deposit</small><b>{peso((selected?.rate||0)*2+(selected?.deposit||0))}</b><span>Final total is calculated securely on submission</span></div><Policy/>{submitError&&<p className="form-error">{submitError}</p>}</div>}
 <Footer back={()=>setStep(step-1)} next={()=>step<5?setStep(step+1):submitBooking()} label={step<5?"Continue":submitting?"Submitting…":"Submit booking request"} disabled={submitting||(step===3&&(!firstName||!lastName||!mobile||!address||!destination))}/></div>}</section>
 <section className="assurance"><div><ShieldCheck/><b>Protected information</b><small>Identity documents stay private.</small></div><div><CircleDollarSign/><b>No hidden pricing</b><small>See rates before submission.</small></div><div><Users/><b>Local support</b><small>Staff review every request.</small></div></section></main>
}
function Header({goAdmin,menu,setMenu}:{goAdmin:()=>void;menu:boolean;setMenu:(v:boolean)=>void}){return <header><Brand/><nav className={menu?"open":""}><a>Fleet</a><a>How it works</a><a>Policies</a><a>Track booking</a><button onClick={goAdmin}>Staff portal</button></nav><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button></header>}
function Heading({n,title}:{n:number;title:string}){return <div className="heading"><div><p className="eyebrow">Step {n} of 5</p><h2>{title}</h2></div><span><i/> Live availability</span></div>}
function Footer({back,next,label,disabled}:{back?:()=>void;next:()=>void;label:string;disabled?:boolean}){return <footer className="stage-foot">{back?<button className="secondary" onClick={back}>Back</button>:<span>Times shown in Asia/Manila</span>}<button className="primary" disabled={disabled} onClick={next}>{label}<ArrowRight/></button></footer>}

const nav=[["Dashboard",LayoutDashboard],["Bookings",CalendarDays],["Customers",Users],["Fleet",CarFront],["Inspections",ShieldCheck],["Finance",CircleDollarSign],["Maintenance",Wrench],["Reports",FileText],["Activity log",Activity],["Settings",Settings]] as const;
function Admin({goCustomer,logout,userEmail}:{goCustomer:()=>void;logout:()=>void;userEmail:string}){
 const[tab,setTab]=useState("Dashboard"),[query,setQuery]=useState(""),[voidRef,setVoidRef]=useState<string|null>(null),[toast,setToast]=useState(""),[rows,setRows]=useState<BookingRow[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 useEffect(()=>{let active=true;async function load(){const supabase=createClient();const{data,error}=await supabase.from("bookings").select("id,booking_reference,booking_status,pickup_at,expected_return_at,reservation_expires_at,estimated_total,customers!inner(first_name,last_name),vehicles!inner(unit_number,vehicle_models!inner(manufacturer,model_name,variant))").order("created_at",{ascending:false}).limit(100);if(!active)return;if(error){setLoadError(error.message);setLoading(false);return}const mapped=(data||[]).map((b:any)=>{const expires=b.reservation_expires_at?new Date(b.reservation_expires_at).getTime()-Date.now():0;const mins=Math.max(0,Math.floor(expires/60000));const model=b.vehicles.vehicle_models;return{id:b.id,ref:b.booking_reference,customer:`${b.customers.first_name} ${b.customers.last_name}`,vehicle:`${model.manufacturer} ${model.model_name}${model.variant?` ${model.variant}`:""} · ${b.vehicles.unit_number}`,trip:`${new Date(b.pickup_at).toLocaleString("en-PH",{timeZone:"Asia/Manila",dateStyle:"medium",timeStyle:"short"})} – ${new Date(b.expected_return_at).toLocaleString("en-PH",{timeZone:"Asia/Manila",dateStyle:"medium",timeStyle:"short"})}`,status:b.booking_status.replaceAll("_"," "),time:b.booking_status==="RESERVED_AWAITING_SETTLEMENT"?`${Math.floor(mins/60)}h ${mins%60}m`:"—",amount:peso(Number(b.estimated_total))}});setRows(mapped);setLoading(false)}load();return()=>{active=false}},[]);
 const filtered=useMemo(()=>rows.filter(r=>(r.ref+r.customer+r.vehicle).toLowerCase().includes(query.toLowerCase())),[query,rows]);
 return <main className="admin"><aside><Brand/><nav>{nav.map(([x,I])=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}><I/>{x}{x==="Bookings"&&rows.length>0&&<em>{rows.length}</em>}</button>)}</nav><button className="customer-link" onClick={goCustomer}><ArrowRight/>Customer site</button><button className="customer-link" onClick={logout}><X/>Sign out</button><div className="profile"><i>OW</i><span><b>Owner</b><small>{userEmail}</small></span></div></aside><section className="admin-main"><header><div><small>Live operations</small><h1>{tab}</h1></div><div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search bookings, customers, plates…"/></label><button><Plus/>New booking</button></div></header>
 {loading&&<div className="fleet-message">Loading live bookings…</div>}{loadError&&<div className="fleet-message error">Could not load bookings: {loadError}</div>}
 {toast&&<div className="toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}
 {tab==="Dashboard"?<Dashboard data={filtered} voidIt={setVoidRef} setTab={setTab}/>:tab==="Bookings"?<Bookings data={filtered} voidIt={setVoidRef}/>:tab==="Fleet"?<Fleet/>:tab==="Finance"?<Finance/>:<Module name={tab}/>}</section>
 {voidRef&&<div className="backdrop"><div className="modal"><i><AlertTriangle/></i><h2>Void booking request?</h2><p>This removes <b>{voidRef}</b> from active queues and immediately releases its vehicle/time-slot hold. Its audit record remains.</p><label>Reason<select><option>Customer entered wrong information</option><option>Customer changed rental details</option><option>Duplicate request</option><option>Wrong vehicle</option><option>Wrong rental schedule</option><option>Customer cancelled</option><option>Other</option></select></label><label>Internal note<textarea placeholder="Add a short explanation…"/></label><footer><button onClick={()=>setVoidRef(null)}>Keep request</button><button className="danger" onClick={()=>{setVoidRef(null);setToast("Booking voided. Its hold is now released.")}}>Void and release hold</button></footer></div></div>}</main>
}
function Dashboard({data,voidIt,setTab}:{data:BookingRow[];voidIt:(x:string)=>void;setTab:(x:string)=>void}){return <><div className="warning"><AlertTriangle/><span><b>Review temporary reservation holds</b><small>Onsite settlement is required before each four-hour deadline.</small></span><button onClick={()=>setTab("Bookings")}>Review holds <ArrowRight/></button></div><div className="metrics">{([["Live bookings",String(data.length),"From Supabase",Clock3],["Active rentals","—","Coming next",CarFront],["Overdue","—","Coming next",AlertTriangle],["Available fleet","—","Live fleet module next",Gauge],["Payments today","—","Finance module next",CircleDollarSign]] as [string,string,string,typeof Clock3][]).map(([a,b,c,I])=><article key={a}><I/><small>{a}</small><b>{b}</b><span>{c}</span></article>)}</div><Table data={data} voidIt={voidIt}/></>}
function PanelHead({title,sub}:{title:string;sub:string}){return <div className="panel-head"><span><h2>{title}</h2><p>{sub}</p></span><button>View all <ArrowRight/></button></div>}
function Table({data,voidIt,all=false}:{data:BookingRow[];voidIt:(x:string)=>void;all?:boolean}){return <section className="panel"><PanelHead title={all?"Active bookings":"Reservations awaiting onsite settlement"} sub={all?"Shared lifecycle, payment, and availability status":"Urgent holds first · server time is authoritative"}/><div className="table"><table><thead><tr><th>Booking</th><th>Customer / vehicle</th><th>Rental schedule</th><th>Status</th><th>{all?"Amount":"Time remaining"}</th><th/></tr></thead><tbody>{data.map(r=><tr key={r.id}><td><b>{r.ref}</b><small>Online request</small></td><td><b>{r.customer}</b><small>{r.vehicle}</small></td><td>{r.trip}</td><td><em className={"s-"+r.status.split(" ")[0].toLowerCase()}>{r.status}</em></td><td><strong>{all?r.amount:r.time}</strong></td><td><button>Open</button><button onClick={()=>voidIt(r.ref)}>•••</button></td></tr>)}</tbody></table></div>{data.length===0&&<div className="fleet-message">No booking requests found.</div>}</section>}
function Bookings({data,voidIt}:{data:BookingRow[];voidIt:(x:string)=>void}){return <div className="module"><div className="module-head"><span><h2>Booking workspace</h2><p>Live requests and rental transactions</p></span><button><Plus/>Walk-in booking</button></div><Table data={data} voidIt={voidIt} all/></div>}
function Fleet(){return <div className="module"><div className="module-head"><span><h2>Fleet catalog</h2><p>Category → model → physical vehicle unit</p></span><button><Plus/>Add vehicle</button></div><div className="stats">{[["Categories","5"],["Models","14"],["Physical units","36"],["Available now","18"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="table"><table><thead><tr><th>Vehicle model</th><th>Category</th><th>Units</th><th>Daily rate</th><th>Deposit</th><th>Visibility</th></tr></thead><tbody>{adminDemoFleet.map((v,i)=><tr key={v.name}><td><b>{v.name}</b><small>{v.transmission} · {v.seats} seats</small></td><td>{v.category}</td><td>{i+2} units</td><td><b>{peso(v.rate)}</b><small>Preview data</small></td><td>{peso(v.deposit)}</td><td><em className="s-ready">Admin preview</em></td></tr>)}</tbody></table></div><div className="rate-note"><Settings/><span><b>Rates are inherited, never hard-coded</b><small>Category defaults can be overridden by model or unit. Approved bookings keep a pricing snapshot.</small></span><button>Edit rates</button></div></div>}
function Finance(){return <><div className="metrics finance">{[["Collected this month","₱382,400","+12.4% vs Aug"],["Outstanding","₱42,800","18 bookings"],["Deposits held","₱91,000","22 active deposits"],["Refunds pending","₱8,500","3 settlements"]].map(x=><article key={x[0]}><CircleDollarSign/><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><div className="module"><div className="module-head"><span><h2>Transaction ledger</h2><p>Balances derive from charges, payments, deposits, and reversals</p></span><button><Plus/>Record payment</button></div>{[["PAY-0924","Payment · Cash","CR-20260903-00124","+ ₱4,500","Posted"],["CHG-0923","Base rental","CR-20260903-00124","₱1,500","Posted"],["DEP-0922","Security deposit","CR-20260903-00124","+ ₱3,000","Held"],["CHG-0921","Overtime · 3 hours","CR-20260902-00119","₱450","Estimated"]].map(x=><div className="ledger" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span><strong>{x[3]}</strong><em>{x[4]}</em></div>)}</div></>}
function Module({name}:{name:string}){return <div className="empty"><i><Settings/></i><h2>{name}</h2><p>This operational workspace is connected to the same authoritative rental lifecycle and audit trail.</p><button className="primary">Open {name.toLowerCase()} <ArrowRight/></button></div>}
function AdminAccess({goCustomer}:{goCustomer:()=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[sessionEmail,setSessionEmail]=useState<string|null>(null),[checking,setChecking]=useState(true),[error,setError]=useState(""),[signingIn,setSigningIn]=useState(false);useEffect(()=>{const supabase=createClient();supabase.auth.getSession().then(({data})=>{setSessionEmail(data.session?.user.email||null);setChecking(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setSessionEmail(session?.user.email||null));return()=>subscription.unsubscribe()},[]);async function login(){setSigningIn(true);setError("");const{error}=await createClient().auth.signInWithPassword({email,password});setSigningIn(false);if(error)setError(error.message)}async function logout(){await createClient().auth.signOut();setSessionEmail(null)}if(checking)return <main className="login"><div className="login-card"><Brand/><p>Checking staff session…</p></div></main>;if(sessionEmail)return <Admin goCustomer={goCustomer} logout={logout} userEmail={sessionEmail}/>;return <main className="login"><div className="login-card"><Brand/><p className="eyebrow">Authorized staff only</p><h1>Staff portal</h1><p>Sign in with your confirmed Supabase owner account.</p><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={signingIn||!email||!password} onClick={login}>{signingIn?"Signing in…":"Sign in"}<ArrowRight/></button><button className="secondary" onClick={goCustomer}>Return to customer site</button></div></main>}
export default function Home(){const[admin,setAdmin]=useState(false);return admin?<AdminAccess goCustomer={()=>setAdmin(false)}/>:<Customer goAdmin={()=>setAdmin(true)}/>}
